apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ccm-linode
  labels:
    app: ccm-linode
  namespace: {{ required ".Values.namespace required" .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: ccm-linode
  template:
    metadata:
      labels:
        app: ccm-linode
    spec:
      serviceAccountName: ccm-linode
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      hostNetwork: true
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: ccm-linode
          args:
            - --leader-elect-resource-lock=leases
            - --v=3
            - --secure-port=10253
            - --webhook-secure-port=0
            {{- if .Values.linodegoDebug }}
            - --linodego-debug={{ .Values.linodegoDebug }}
            {{- end }}
            {{- if .Values.routeController }}
            - --enable-route-controller=true
            {{- if .Values.routeController.vpcName }}
            - --vpc-name={{ "A valid .Values.routeController.vpcName is required" .Values.routeController.vpcName }}
            {{- end }}
            {{- if .Values.routeController.vpcNames }}
            - --vpc-names={{ "A valid .Values.routeController.vpcNames is required" .Values.routeController.vpcNames }}
            {{- end }}
            - --configure-cloud-routes={{ default true .Values.routeController.configureCloudRoutes }}
            - --cluster-cidr={{ required "A valid .Values.routeController.clusterCIDR is required" .Values.routeController.clusterCIDR }}
            {{- if .Values.routeController.routeReconciliationPeriod }}
            - --route-reconciliation-period={{ .Values.routeController.routeReconciliationPeriod }}
            {{- end }}
            {{- end }}
            {{- if .Values.sharedIPLoadBalancing }}
            {{- if .Values.sharedIPLoadBalancing.bgpNodeSelector }}
            - --bgp-node-selector={{ .Values.sharedIPLoadBalancing.bgpNodeSelector }}
            {{- end }}
            - --load-balancer-type={{ required "A valid .Values.sharedIPLoadBalancing.loadBalancerType is required for shared IP load-balancing" .Values.sharedIPLoadBalancing.loadBalancerType }}
            {{- end }}
          volumeMounts:
            - mountPath: /etc/kubernetes
              name: k8s
            {{- with .Values.volumeMounts}}
            {{- toYaml . | nindent 12 }}
            {{- end}}
          env:
            - name: LINODE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.secretRef }}{{ .Values.secretRef.name | default "ccm-linode" }}{{ else }}"ccm-linode"{{ end }}
                  key: {{ if .Values.secretRef }}{{ .Values.secretRef.apiTokenRef | default "apiToken" }}{{ else }}"apiToken"{{ end }}
            - name: LINODE_REGION
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.secretRef }}{{ .Values.secretRef.name | default "ccm-linode" }}{{ else }}"ccm-linode"{{ end }}
                  key: {{ if .Values.secretRef }}{{ .Values.secretRef.regionRef | default "region" }}{{ else }}"region"{{ end }}
            {{- with .Values.env}}
            {{- toYaml . | nindent 12 }}
            {{- end}}
      volumes:
        - name: k8s
          hostPath:
            path: /etc/kubernetes
        {{- with .Values.volumes}}
        {{- toYaml . | nindent 8 }}
        {{- end}}
